name: CI

on:
  # run on pushed commits to master and on new commits on pull requests
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  Security:
    name: Security Pipeline
    uses: uc-cdis/.github/.github/workflows/securitypipeline.yaml@master
    with:
       python-poetry: 'false'
    secrets: inherit  # pragma: allowlist secret
  UnitTest:
    name: Python Unit Test
    uses: uc-cdis/.github/.github/workflows/python_unit_test.yaml@master
    strategy:
      matrix:
        # the versions for which we require the CI to pass on PRs can
        # be updated in the repo settings (branch rules)
        version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    with:
        python-version: ${{ matrix.version }}
